package dnddiceroller;

import java.util.Random;

/**
 * @author Rhonda Marshall
 * Oct 19, 2015
 */
public class Die {
    private int numberOfSides;             // number of sides on the dice
    private int value;                     // value generated by a random number 
    
    /**
     * Constructor
     * @param numberOfSides     The numberOfSides on the dice
     */
    public Die(int numberOfSides) {
        this.numberOfSides = numberOfSides;
        this.value = 0;
    } // Die constructor
    
    /**
     * The roll methods 
     * - Calculates a random number between the value
     *   of one and the Die objects numberOfSides field.
     * - Sets the Die objects value field to equal the random number
     */
    public void roll() {
        // Create a Random class object
        Random randomNumber = new Random();
        this.value = randomNumber.nextInt(this.numberOfSides) + 1;   
    }
    
    
    /**
     * getValue accessors method
     * @return  The Die objects value
     */
    public int getValue(){
        return this.value;
    } // getValue
       
} // Die class


