package dnddiceroller;

import java.util.Random;

/**
 *
 * @author Rhonda Marshall
 * Oct 19, 2015
 */
public class Die {
    public int numberOfSides;             // number of sides on the dice
    public int value;                     // value generated by a random number
    private final Boolean debug;          // for my debugging purposes
    
    /**
     * Constructor
     * @param numberOfSides     The numberOfSides on the dice
     */
    public Die(int numberOfSides) {
        this.numberOfSides = numberOfSides;
        this.value = 0;
        this.debug = false;
        
    } // Die constructor
    
    /**
     * The roll methods 
     * - Calculates a random number between the value
     *   of one and the Die objects numberOfSides field.
     * - Sets the Die objects value field to equal the random number
     */
    public void roll() {
        // Create a Random class object
        Random randomNumber = new Random();
        this.value = randomNumber.nextInt(this.numberOfSides) + 1;
        if (this.debug)
            System.out.printf("roll: random number is %d\n", this.value);
    }
    
    
    /**
     * getValue accessors method
     * @return  The Die objects value
     */
    public int getValue(){
        return this.value;
    } // getValue
       
} // Die class


